### ISSUE TITLE
[ Feature Request ] : Testing for a list of url's

### ISSUE THREAD

**Issue by osamahamad** [EnableSecurity/wafw00f#112]
Hi , 

For now I'm doing something like 

```
for i in $(cat domains.out);do wafw00f $i -r | tail -n +15 | tee -a waf-detection.out ;done 
```
+ tryin to find better ways so I can test a list of domains xd.

I hope to see this great tool have option to detect list of domains with concurrency set in mind and provide a proper simple text output for the results. That will be so much helpful.

**Comment by sandrogauci** [comment]
please use the `-i` flag which takes lists of URLs (and tries to form a URL out of hostnames). For help, `--help`.

**Comment by osamahamad** [comment]
Thanks! and apologize. I just realized that I've been using version 1.0.0 :)
