### ISSUE TITLE
Old verson installed with apt install

### ISSUE THREAD

**Issue by aaaguirrep** [EnableSecurity/wafw00f#116]
**Describe the bug**
When I run ```apt install wafw00f``` it installs an old version of wafw00f.

**To Reproduce**
```apt install wafw00f```

**Expected behavior**
Last version installed

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux] Linux e40bb9da847e 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - OS version, distribution: Ubuntu
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
 - Python version: [e.g. python 3.2] python3

**Debug output**
```
➜  / wafw00f -V

                                 ^     ^
        _   __  _   ____ _   __  _    _   ____
       ///7/ /.' \ / __////7/ /,' \ ,' \ / __/
      | V V // o // _/ | V V // 0 // 0 // _/
      |_n_,'/_n_//_/   |_n_,' \_,' \_,'/_/
                                <
                                 ...'

    WAFW00F - Web Application Firewall Detection Tool

    By Sandro Gauci && Wendel G. Henrique

WAFW00F version 0.9.4
```

**Additional context**

**Comment by sandrogauci** [comment]
Hi there .. we do not maintain distro-specific packages. We recommend installing wafw00f through `pip` or `setup.py`.

You are most welcome to file an issue in the relevant packaging system urging them to upgrade :)

**Comment by 0xInfection** [comment]
Ubuntu 20.04 LTS has the latest version of wafw00f. 
> Source: https://packages.ubuntu.com/focal/wafw00f

Also `groovy` seems to have an upgraded version too. -> https://packages.ubuntu.com/groovy/wafw00f
