### ISSUE TITLE
anquangou

### ISSUE THREAD

**Issue by TanGe0** [EnableSecurity/wafw00f#121]
![image](https://user-images.githubusercontent.com/59207686/102601069-a1106380-415a-11eb-935a-22635414eb1e.png)
![image](https://user-images.githubusercontent.com/59207686/102601133-b71e2400-415a-11eb-9112-c1f215318a00.png)

**Comment by 0xInfection** [comment]
Please give some context in this is about.

**Comment by TanGe0** [comment]
> 请提供有关此内容的背景信息。

I installed safdog in the range, but waff00f didn't detect it

**Comment by TanGe0** [comment]
> 请提供有关此内容的背景信息。

I installed safdog in the range, but waff00f didn't detect it

**Comment by sandrogauci** [comment]
closing for now. If there's further information about how it should be detected, please add a comment
