### ISSUE TITLE
Don't work on Windows

### ISSUE THREAD

**Issue by user12243** [EnableSecurity/wafw00f#135]
**Describe the bug**
I installed wafw00f on windows, write in the command line setup.py install it is installed then I enter setup.py --help everything works but when I enter setup.py --url https://test.com it knocks out the link https: // github.com/enablesecurity/wafw00f and that's all
tried python 2.8, 3.8, 3.9 doesn't help

**Comment by sandrogauci** [comment]
Please follow the [getting started](https://github.com/enablesecurity/wafw00f/wiki/Getting-Started). It seems that you should be using the `wafw00f` command rather than `setup.py`. The issues are for bug reports etc so please do use the relevant bug report template in the future.

**Comment by user12243** [comment]
> It seems that you should be using the `wafw00f` command rather than `setup.py`

"wafw00f" is not internal or external
command, executable program, or batch file.
