### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by user12243** [EnableSecurity/wafw00f#136]
I installed wafw00f on windows, write in the command line setup.py install it is installed then I enter setup.py --help everything works but when I enter setup.py --url https://test.com it knocks out the link https: // github.com/enablesecurity/wafw00f and that's all I tried to enter krmanda wafw00f but knocks out "wafw00f" is not internal or external
command, executable program, or batch file.

**Comment by 0xInfection** [comment]
Please make an effort of reading the readme at least before installing/using any tool.
