### ISSUE TITLE
About the timeout of request and WAF block 

### ISSUE THREAD

**Issue by anquanbiji** [EnableSecurity/wafw00f#156]
Hi everyone

If the request can't be responsed in 7 seconds or blocked by WAF,  the function of **identwaf** will stop to detect and return with exception **RequestBlocked**. 

As we know, some WAF can be detected by normal request.  

So can you add the default timeout of every request and continue to detect the WAF when there is the exception **RequestBlocked**?

Thanks for your answer.

**Comment by sandrogauci** [comment]
Sorry for the late answer. This seems too vague to me - can you be more specific? I'll close this - feel free to reopen. Make sure to answer the following:

- what your expectations?
- what is the actual behavior which differs from your expectations?
- can we test this somewhere?
