### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by asterictnl-lvdw** [EnableSecurity/wafw00f#157]
Hi Team,

I found an way to execute wafw00f on Windows:

`cd C:\Temp && powershell -Command wget -O C:\temp\wafw00f.zip https://github.com/EnableSecurity/wafw00f/archive/master.zip && powershell -Command Expand-Archive -Path C:\Temp\wafw00f.zip -DestinationPath C:\Temp\ -force && cd C:\Temp\wafw00f-master && pip3 install . && cd .\wafw00f && python main.py https://example.com`

Maybe this can be improved towards building an .exe of wafw00f? Maybe with pyinstaller? I haven't found the correct packages and such that should be added to the .spec file. 

Let me know if you need any more info.

**Comment by Zaeem20** [comment]
you can create a pull requests and they will merge it after reviewing ...

**Comment by sandrogauci** [comment]
@asterictnl-lvdw what @Zaeem20 said :) We don't currently provide binaries - if you think that we should and could add a PR then I'll be happy to review that.
