### ISSUE TITLE
Collections Mapping

### ISSUE THREAD

**Issue by gusmaocool** [EnableSecurity/wafw00f#164]
HI, 
when running wafw00f it is returning me this error.

![image](https://user-images.githubusercontent.com/28679008/191576624-7d628468-9e31-401c-bccf-bbc7a46af655.png)

could someone support?

**Comment by Zaeem20** [comment]
Noted Issue, i will make a pull request soon to project

**Comment by Zaeem20** [comment]
Hey i will suggest you to use this in python 3.9, this issue is causing by Python Version

**Comment by 0xInfection** [comment]
This actually looks like a issue reproducible using Python 3.10 but not Python 3.9. Would you mind testing this out with Python 3.9 and tell us if the issue still persists? Thanks!

**Comment by 0xInfection** [comment]
Closing this for now, feel free to reopen this if the issue is reproducible using other versions as well.

**Comment by gusmaocool** [comment]
tks for all support
