### ISSUE TITLE
wafw00f no response

### ISSUE THREAD

**Issue by baoerjiea** [EnableSecurity/wafw00f#176]
It doesn't respond when I only use it，there is also no error message。

**Comment by ay-githubs** [comment]
ImportError: cannot import name 'Color' from 'wafw00f.lib.asciiarts' (E:\ruanjian\python3.10\lib\site-packages\wafw00f\lib\asciiarts.py)

**Comment by 0xInfection** [comment]
Hi @baoerjiea , can you mention the command that triggers this behaviour? Would be great if I can reproduce it.

**Comment by 0xInfection** [comment]
Closing this issue for now. Feel free to reopen this with more details.
