### ISSUE TITLE
Change param name of request

### ISSUE THREAD

**Issue by mikhailevtikhov** [EnableSecurity/wafw00f#178]
The problem is that the parameter name of url which wafw00f generate is too simple, for example "s", and there are applications for which this parameter is really significant and the page that returns to the request with such a parameter is different from the "malicious request" without such a parameter, which leads to a false trigger, because wafw00f believes that this behavior indicates the triggering of the WAF, but in fact, it is the backend server that processed the request.

In order to exclude the possibility of such an event, a function was implemented that returns a random sequence of 8 ascii lowercases letters and this string is used as a parameter for the request, thereby the probability that this parameter will be significant for the server is being streamed to 0.

Random string of 8 ascii lowercases letters and used it as a parameter for the request is implemented in this PR - https://github.com/vulnspace/wafw00f/pull/2

**Comment by 0xInfection** [comment]
Good catch! Will merge in the changes.
