### ISSUE TITLE
python setup.py install command not work

### ISSUE THREAD

**Issue by Druyaj018** [EnableSecurity/wafw00f#185]
Hi,
python setup.py install command not work
![notwork](https://github.com/EnableSecurity/wafw00f/assets/112065021/aadbf0f8-eb7e-444e-b3da-6e9bb1eb3d2f)

**Comment by Se5sion** [comment]
I got the same problem.

**Comment by Se5sion** [comment]
> 我遇到了同样的问题。

actually,wow,I tried to flip the install command and just go to use the wafw00f and it works...maybe it had been installed when clone done,and the py command is for another version provided.

**Comment by Se5sion** [comment]
I try to flip the install command and just go to use the wafw00f instead, this time it works...maybe it had been installed when clone done,and the py command is for another version provided.

**Comment by foozzi** [comment]
> I try to flip the install command and just go to use the wafw00f instead, this time it works...maybe it had been installed when clone done,and the py command is for another version provided.

Hi,
You can install my fork for now - https://github.com/foozzi/wafw00f
I have added the 'Hatch' project manager.

**Comment by ism** [comment]
@Druyaj018 @Se5sion running ```pip install --upgrade setuptools``` solved it for me

**Comment by 0xInfection** [comment]
closing this issue as `ism` found a fix for it.
