### ISSUE TITLE
Integration 

### ISSUE THREAD

**Issue by morpheuslord** [EnableSecurity/wafw00f#186]
Hello there,

I have been looking into your project and it's great I just wanted to add a few doubts about integration. I am currently working on a project known as GPT-Vuln_Analyzer and as of now it has a few recon capabilities I wanted to integrate your waf scanner into the framework if possible and if you don't mind I wanted to ask how I can use the modules defined for the task. A wiki on it would be great.
thank you.

**Comment by 0xInfection** [comment]
closing as related to #195.
