### ISSUE TITLE
Error in line 22 of the main.py file

### ISSUE THREAD

**Issue by KarryDavid** [EnableSecurity/wafw00f#189]
**Error in line 22 of the main file:**
<img width="831" alt="iShot_2023-10-24_14 23 04" src="https://github.com/EnableSecurity/wafw00f/assets/148523813/5157daec-52f3-4f81-99e3-f4852ce21615">

I can't run the main.py
macbookpro M1 11.6.    python3.11.    the latest wafw00f

**Comment by Zaeem20** [comment]
can you specify which python or pip version you are using?

**Comment by foozzi** [comment]
> **Error in line 22 of the main file:** <img alt="iShot_2023-10-24_14 23 04" width="831" src="https://user-images.githubusercontent.com/148523813/277566848-5157daec-52f3-4f81-99e3-f4852ce21615.png">
> 
> I can't run the main.py macbookpro M1 11.6. python3.11. the latest wafw00f

You can't run it without installation because of the architecture of the app.

**Comment by KarryDavid** [comment]
> > **主文件第22行错误：** <img alt="iShot_2023-10-24_14 23 04" width="831" src="https://user-images.githubusercontent.com/148523813/277566848-5157daec-52f3-4f81-99e3-f4852ce21615.png">
> > 我无法运行 main.py macbookpro M1 11.6。python3.11。最新的wafw00f
> 
> 由于应用程序的架构，您无法在不安装的情况下运行它。 您可以将 main.py 重命名为`__main__.py`，然后尝试使用`python -m wafw00f`

Because it takes too much time to download the application, I tried to run it directly, and I can run it successfully through your method.
