### ISSUE TITLE
HTTPSConnectionPool port 443 conduct to Read timed out - response time from the server is too low?

### ISSUE THREAD

**Issue by carboncrystal** [EnableSecurity/wafw00f#191]
**Describe the bug**
Some websites are seen as down by wafw00f, but this websites are up.

**To Reproduce**
wafw00f https://www.tesla.com
RESULT IN:
[*] Checking https://www.tesla.com
ERROR:wafw00f:Something went wrong HTTPSConnectionPool(host='www.tesla.com', port=443): Read timed out. (read timeout=7)
ERROR:wafw00f:Site www.tesla.com appears to be down

**Expected behavior**
tesla.com is not down, but wafw00f see it is down.

**Desktop (please complete the following information):**
 - OS: 22.04.3 LTS
 - Python version: Python 3.10.12

**Debug output**
wafw00f https://www.tesla.com -vv

```
[*] Checking https://www.tesla.com
INFO:wafw00f:starting wafw00f on https://www.tesla.com
ERROR:wafw00f:Something went wrong HTTPSConnectionPool(host='www.tesla.com', port=443): Read timed out. (read timeout=7)
ERROR:wafw00f:Site www.tesla.com appears to be down
```

**Additional context**
I think wafw00f needs to be adapted to the new urllib3 changes. Does wafw00f have a PoolManager? Maybe PoolManager will automatically handle HTTPSConnectionPool objects and these kind of errors will be a thing of the past.

**Comment by 0xInfection** [comment]
hmm, I think this particular case is weird, I cannot even make a query with curl -- it times out. no matter what i do, user-agents / cookies, etc, I cannot connect to the host. feel free to reopen, if you do find a workaround.
