### ISSUE TITLE
code plugin

### ISSUE THREAD

**Issue by HalilDeniz** [EnableSecurity/wafw00f#194]
Hello.
I'm creating a port scanning tool. and I will add web firewall detection to my tool using the wafw00f module. Can you give an example code that works with the function?

and this is my tool:
https://github.com/HalilDeniz/NetworkSherlock

**Comment by Zaeem20** [comment]
in wafw00f there is a method named idenwaf()... you can use that method...

**Comment by 0xInfection** [comment]
closing in as closely related to #195.
