### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by qh03n1x** [EnableSecurity/wafw00f#200]
/usr/local/bin/wafw00f:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html                                                                   
  __import__('pkg_resources').run_script('wafw00f==2.2.0', 'wafw00f')

**Comment by ItsIgnacioPortal** [comment]
Here's more information:
```
DEPRECATION: Loading egg at c:\python311\lib\site-packages\pluginbase-1.0.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
```
https://github.com/pypa/pip/issues/12330
