### ISSUE TITLE
UBIKA WAF detection

### ISSUE THREAD

**Issue by orielo** [EnableSecurity/wafw00f#208]
Is it possible to add  UBIKA to the coverage of this tool?

**Comment by 0xInfection** [comment]
I believe Ubika is the renovated version of DenyAll (for which we already have detection for). Not sure if much has changed in terms of fingerprints. If you have an instance of such a WAF running you can provide it to us to speed up the addition of the WAF. Feel free to DM me on twitter if the instance cannot be shared publicly. :)

**Comment by 0xInfection** [comment]
closing this as no updates, feel free to reopen!
