### ISSUE TITLE
Add support for Edgecast / Verizon Digital media WAF

### ISSUE THREAD

**Issue by kkirsche** [EnableSecurity/wafw00f#39]
https://www.verizondigitalmedia.com/blog/2014/12/a-waf-for-all-reasons-the-verizon-waf-is-now/

**Comment by sandrogauci** [comment]
thanks for the request @kkirsche .. can you provide some details as to how it may be detected? 

Is the regex for the Server header `ECD \(.*?\)` an effective way to detect it?

**Comment by kkirsche** [comment]
Yes, that will detect that it's part of the distribution network which the WAF is integrated into. Also, anything that applies to ModSecurity has the potential to detect it as the solution is based on ModSecurity (disclosed on https://www.verizondigitalmedia.com/bm-waf-whitepaper/)

**Comment by sandrogauci** [comment]
In the past, we all the ModSecurity checks resulted in false positives and false negatives; i.e. they were terrible checks. If you can come up with a good check, please do share

**Comment by kkirsche** [comment]
Looks correct to me. Just tested it. Thanks for implementing this 👍
