### ISSUE TITLE
error with install ?

### ISSUE THREAD

**Issue by bahoffman** [EnableSecurity/wafw00f#50]
I install - 
<pre><font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~</b></font># pip install wafw00f
Collecting wafw00f
  Downloading wafw00f-0.9.4.tar.gz
Collecting beautifulsoup4==4.4.1 (from wafw00f)
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 588kB/s 
Collecting pluginbase==0.3 (from wafw00f)
  Downloading pluginbase-0.3-py2-none-any.whl
Building wheels for collected packages: wafw00f
  Running setup.py bdist_wheel for wafw00f ... done
  Stored in directory: /root/.cache/pip/wheels/79/ce/04/86e806fc62bf5d51878808f48ca4ce8dbe4719178fac9afacd
Successfully built wafw00f
Installing collected packages: beautifulsoup4, pluginbase, wafw00f
  Found existing installation: beautifulsoup4 4.6.0
    Not uninstalling beautifulsoup4 at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed beautifulsoup4-4.4.1 pluginbase-0.3 wafw00f-0.9.4
</pre>

but get
<pre><font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~</b></font># wafw00f -l
Traceback (most recent call last):
  File &quot;/usr/local/bin/wafw00f&quot;, line 4, in &lt;module&gt;
    from wafw00f import main
  File &quot;/usr/local/lib/python2.7/dist-packages/wafw00f/main.py&quot;, line 53, in &lt;module&gt;
    from wafw00f.lib.evillib import oururlparse, scrambledheader, waftoolsengine
  File &quot;/usr/local/lib/python2.7/dist-packages/wafw00f/lib/evillib.py&quot;, line 14, in &lt;module&gt;
    from bs4 import BeautifulSoup
  File &quot;/usr/local/lib/python2.7/dist-packages/bs4/__init__.py&quot;, line 30, in &lt;module&gt;
    from .builder import builder_registry, ParserRejectedMarkup
  File &quot;/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py&quot;, line 314, in &lt;module&gt;
    from . import _html5lib
  File &quot;/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py&quot;, line 70, in &lt;module&gt;
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: &apos;module&apos; object has no attribute &apos;_base&apos;
</pre>

Any recommendation ?

**Comment by sandrogauci** [comment]
html5lib incompatability. Could you test the version from the repo? i.e. `git clone https://github.com/EnableSecurity/wafw00f.git` ?

**Comment by bahoffman** [comment]
Sorry for the bother. I updated a lot of system stuff and it put things right. Thank you
