### ISSUE TITLE
error running program from git install

### ISSUE THREAD

**Issue by Gam-7** [EnableSecurity/wafw00f#51]
root@kali:~/Downloads/pentest/tools/wafw00f/wafw00f# uname -a
Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali1 (2018-01-08) x86_64 GNU/Linux

root@kali:~/Downloads/pentest/tools/wafw00f/wafw00f# wafw00f -l
Traceback (most recent call last):
  File "/usr/local/bin/wafw00f", line 4, in <module>
    __import__('pkg_resources').run_script('wafw00f==0.9.4', 'wafw00f')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1429, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/wafw00f' not found in metadata at '/usr/local/lib/python2.7/dist-packages/wafw00f-0.9.4.dist-info'

Hi Any Ideas (I am running this on a persistent USB)

**Comment by sandrogauci** [comment]
Do a the following

```
git clone https://github.com/EnableSecurity/wafw00f.git
cd wafw00f
python setup.py install
wafw00f -l
```

Your wafw00f installation appears to be broken, so please update that and your required python packages too.

**Comment by Gam-7** [comment]
Thanks [solved]
