### ISSUE TITLE
Could not initialize connection to www.domain.com

### ISSUE THREAD

**Issue by jordantsap** [EnableSecurity/wafw00f#68]
I use parrot os and i used python setup.py install to install it.
When i use wafw00f https://nea-karvali.gr/ with no arguments the output is:
ERROR:root:Site https://www.nea-karvali.gr/ appears to be down.
When using -v option gives me:
WARNING:wafw00f:Could not initialize connection to www.nea-karvali.gr

Whats wrong here?

**Comment by sandrogauci** [comment]
I cannot reproduce the issue. Unfortunately I cannot help you with the limited information that you provided. If you reopen the issue, please provide further information. Test with curl or a similar tool, provide pcap etc.
