### ISSUE TITLE
There was an error in the setup.py  "TypeError: ' Encoding ' is a invalid keyword argument for this function"

### ISSUE THREAD

**Issue by Cu0rly** [EnableSecurity/wafw00f#79]
Workaround：
![issue](https://user-images.githubusercontent.com/48941076/58941106-ad69e100-87ad-11e9-923f-9713d51dd47a.png)

**Comment by 0xInfection** [comment]
Hi Cu0rly, thank you for pulling this up, I appreciate the fact that you also hinted at a work-around. Will be fixed within 10.

**Comment by 0xInfection** [comment]
Fixed via d59d9b1 in #80.
