### ISSUE TITLE
Issues with Python 2

### ISSUE THREAD

**Issue by NishealJ** [EnableSecurity/wafw00f#82]
**Describe the bug**

While installing wafw00f in python 2.7 the setup is not smooth because beautifulsoup4, soupsieve needs backports.functools_lru_cache to work well with python 2.7 i believe we should add backports.functools_lru_cache dependencies for an error-free installation in python 2.7

**To Reproduce**
Try setup.py in python 2.7

**Screenshots**
<img width="567" alt="Screenshot 2019-06-11 at 11 00 11 AM" src="https://user-images.githubusercontent.com/41017303/59254040-1b902700-8c38-11e9-8671-0c2d0f5a4b47.png">

**Comment by sandrogauci** [comment]
Removed the dependency for bs4 in a95a94253f138d5ef791232ef4d8371de41622b6 - can you let me know if this resolves it?

Background (for @0xInfection and contributors): bs4 was required in `evillib.py` which was used in some of my internal tools (like waffit that never got released). It was never needed for wafw00f itself.

**Comment by NishealJ** [comment]
Works perfect, Thanks @sandrogauci
