### ISSUE TITLE
wafw00f not working

### ISSUE THREAD

**Issue by thechampanurag** [EnableSecurity/wafw00f#86]
I cloned repo and installed on my OSX system, but nothing is working, getting following error
```
Traceback (most recent call last):
  File "/Users/anuraggoel/opt/anaconda3/bin/wafw00f", line 4, in <module>
    __import__('pkg_resources').run_script('wafw00f==1.0.0', 'wafw00f')
  File "/Users/anuraggoel/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/anuraggoel/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/wafw00f' not found in metadata at '/Users/anuraggoel/wafw00f/wafw00f.egg-info'
(base) Anurags-MacBook-Pro:wafw00f anuraggoel$ wafw00f -h
Traceback (most recent call last):
  File "/Users/anuraggoel/opt/anaconda3/bin/wafw00f", line 4, in <module>
    __import__('pkg_resources').run_script('wafw00f==1.0.0', 'wafw00f')
  File "/Users/anuraggoel/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/anuraggoel/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/wafw00f' not found in metadata at '/Users/anuraggoel/wafw00f/wafw00f.egg-info'
```

**Comment by 0xInfection** [comment]
Hi, thanks for reporting this. I think this is a problem regarding your installation environment. Would you care to elaborate how you installed `wafw00f`?

**Comment by thechampanurag** [comment]
Hi, I just cloned the repository and installed it with setup.py (python setup.py install).
I tried on both Python 2.7.16 and Python 3.7.4

**Comment by sandrogauci** [comment]
can you share the output from setup.py please?
I don't have an OSX handy right now to test this on but on a Fedora, installation works fine on both Python 2.7.17 and Python 3.7.5.

Based on the paths in the errors, it does seem that not running a standard (vanilla) Python installation, but Anaconda which I'm not familiar with so that might be related.

**Comment by sandrogauci** [comment]
closing unless anyone else is facing the same issue. It seems specific to @thechampanurag 's setup.

**Comment by shagunattri** [comment]
I have similar error where I clone the repo and install wafw00f using 
```
python setup.py install
```
But  
```
 wafw00f --help 
```
results in

```
Traceback (most recent call last):
  File "/usr/bin/wafw00f", line 4, in <module>
    __import__('pkg_resources').run_script('wafw00f==2.1.0', 'wafw00f')
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/wafw00f' not found in metadata at '/usr/lib/python3.8/site-packages/wafw00f-2.1.0-py3.8.egg-info'
```

Device Details:
```
Linux id10t 5.3.18-1-MANJARO #1 SMP PREEMPT Wed Dec 18 18:34:35 UTC 2019 x86_64 GNU/Linux

```
@sandrogauci

**Comment by d0dg3r4m** [comment]
Hello 
I just had a problem like that.

pkg_resources.ResolutionError: Script 'scripts/wafw00f' not found in metadata at '/usr/local/lib/python3.11/dist-packages/wafw00f-2.2.0.dist-info'

So I downloaded the repository and followed the installation, and to run wafw00f, I used the repository path:
└─$ sudo python3 ~/wafw00f/wafw00f/bin/wafw00f https://domain.com

**Comment by mastercho** [comment]
I have same issue also like previous user reported

> closing unless anyone else is facing the same issue. It seems specific to @thechampanurag 's setup.

**Comment by Hunt3rBugB0unty** [comment]
Hello,
Facing similar issue. When trying to run wafw00f, I get the following:

pkg_resources.ResolutionError: Script 'scripts/wafw00f' not found in metadata at '/usr/local/lib/python3.10/dist-packages/wafw00f-2.2.0.dist-info'

I installed it by following steps:

git clone https://github.com/EnableSecurity/wafw00f.git ~/tools/waff00f
cd ~/tools/wafw00f
sudo python3 setup.py install
